config/routes.rb
Rails.application.routes.draw do
  resources :sections
  resources :samboks
  root "home#main"
  
  get 'home/index'
  get 'home/main'

end

app/models/sambok.rb
class Sambok < ActiveRecord::Base
end

app/models/section.rb
class Section < ActiveRecord::Base
    def devide(spliter: false, section: 'subtitle')
        # <p class="section-subtitle" style="text-align: center;">청년영상제작크루 삼복프로덕션은 모바일에 특화된 영상콘텐츠를 만드는</p>
        result = self.content.split('///').map { |sentance|
            s = sentance.split('')
            s.pop; s.pop
            
            case section
            when 'subtitle'
                unless s.join.length.zero?
                    if s.join.length == 1
                        @result = '<p class="section-subtitle" style="text-align: center;">&nbsp;</p>'
                    else
                        @result = '<p class="section-subtitle" style="text-align: center;">' + s.join + '</p>'
                    end
                end
            when 'content'
                unless s.join.length.zero?
                    if s.join.length == 1
                        @result = '<p class="section-content" style="text-align: center;">&nbsp;</p>'
                    else
                        @result = '<p class="section-content" style="text-align: center;">' + s.join + '</p>'
                    end
                end
            end
            
            @result
        }[1..-1]
        
        return result if spliter
        return result.join unless spliter
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    # protect_from_forgery with: :exception
    
    $app_url    = "http://sambok161227-yhk1038.c9users.io"
    $app_title  = "SAMBOK PRODUCTION"
    $app_description = "MAKING WHAT THE WORLD WANTS"
    $app_logo_path = "/asset/header/img/logo.png"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
    
    def main
        @sambok = Sambok.first
        @sections = Section.all
        # @img_url = "http://res.cloudinary.com/hrscywv4p/image/upload/c_limit,h_630,w_1200,f_auto/v1/1084360/a_cckkf8.png"
        # @img_url = "/asset/header/img/original_logo.png"
        @img_url = "/asset/header/img/sambok_text_logo.png"
        
        # @bg_pink_img = "https://uploads.strikinglycdn.com/static/backgrounds/pastel-solids/39.jpg"
        @bg_pink_img = "/asset/header/img/bg_pink_img.jpg"
        
        # Font-Controll
        @main_title_size = 40
        @section_title_size = 24 # px
        @section_subtitle_size = 23 # px
        @section_content_size = 20 # px
    end
end

app/controllers/samboks_controller.rb
class SamboksController < ApplicationController
  before_action :set_sambok, only: [:show, :edit, :update, :destroy]
  layout 'sambok'

  # GET /samboks
  # GET /samboks.json
  def index
      @samboks = Sambok.all
      @sections = Section.all
  end

  # GET /samboks/1
  # GET /samboks/1.json
  def show
  end

  # GET /samboks/new
  def new
    @sambok = Sambok.new
  end

  # GET /samboks/1/edit
  def edit
  end

  # POST /samboks
  # POST /samboks.json
  def create
    @sambok = Sambok.new(sambok_params)

    respond_to do |format|
      if @sambok.save
        format.html { redirect_to @sambok, notice: 'Sambok was successfully created.' }
        format.json { render :show, status: :created, location: @sambok }
      else
        format.html { render :new }
        format.json { render json: @sambok.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samboks/1
  # PATCH/PUT /samboks/1.json
  def update
    respond_to do |format|
      if @sambok.update(sambok_params)
        format.html { redirect_to @sambok, notice: 'Sambok was successfully updated.' }
        format.json { render :show, status: :ok, location: @sambok }
      else
        format.html { render :edit }
        format.json { render json: @sambok.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samboks/1
  # DELETE /samboks/1.json
  def destroy
    @sambok.destroy
    respond_to do |format|
      format.html { redirect_to samboks_url, notice: 'Sambok was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sambok
      @sambok = Sambok.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sambok_params
      params.require(:sambok).permit(:name, :slogan, :img_path)
    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  before_action :set_section, only: [:show, :edit, :update, :destroy]
  layout 'sambok'
  
  # GET /sections
  # GET /sections.json
  def index
    @sections = Section.all
  end

  # GET /sections/1
  # GET /sections/1.json
  def show
  end

  # GET /sections/new
  def new
    @section = Section.new
  end

  # GET /sections/1/edit
  def edit
  end

  # POST /sections
  # POST /sections.json
  def create
    @section = Section.new(section_params)

    respond_to do |format|
      if @section.save
        format.html { redirect_to @section, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sections/1
  # PATCH/PUT /sections/1.json
  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @section, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sections/1
  # DELETE /sections/1.json
  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to sections_url, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_section
      @section = Section.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def section_params
      params.require(:section).permit(:name, :subtitle, :subtitle_size, :subtitle2, :subtitle2_size, :content, :img_path, :bg_img_path)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/samboks_helper.rb
module SamboksHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/views/home/_custom_css.html.erb
<style>


#header-container .nav-item a,
#header-container-fixed .nav-item a {
	border-bottom: 0px !important;
	font-weight: 300;
	transition: all 0.4s ease;
}

#header-container .nav-item a:hover {
	color: #b42a3c !important;
}

#header-container-fixed .nav-item a:hover {
	font-weight: 600;
}

#header-container {
    padding: 45px 0 25px;
}

</style>

app/views/js/_first.html.erb
<script type="text/javascript">
    window.NREUM || (NREUM = {});
    NREUM.info = {
        "beacon": "bam.nr-data.net",
        "errorBeacon": "bam.nr-data.net",
        "licenseKey": "74f55de04c",
        "applicationID": "4870173",
        "transactionName": "IlcLQxBeWFoHShYWSgRKOkQLRVFFTUtRDE4=",
        "queueTime": 1,
        "applicationTime": 310,
        "agent": "",
        "atts": "GhoQFVhKFlAXVFU8TBNURw1AWUBCEgIWTEoAVQdYCR9HQhBRUgpXBlQcGQFeWRlARUQ="
    }
</script>

app/views/js/_googleapis.html.erb
<script>
    var _gaq = _gaq || [];
    if ($S.stores.pageMeta.exception_tracking) {
    /* load errorception */
    var _errs=["518ac810441fb4b7180002fa"];(function(a,b){a.onerror=function(){_errs.push(arguments)};
    var d=function(){var a=b.createElement("script"),c=b.getElementsByTagName("script")[0];
    a.src="//d15qhc0lu1ghnk.cloudfront.net/beacon.js";a.async=!0;
    c.parentNode.insertBefore(a,c)};a.addEventListener?a.addEventListener("load",d,!1):
    a.attachEvent("onload",d)})(window,document);
    }
    
    // Google Analytics (Universal) Setup
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','__ga');
    
    // configuration for keen.io
    var Keen=Keen||{configure:function(e){this._cf=e},addEvent:function(e,t,n,i){this._eq=this._eq||[],this._eq.push([e,t,n,i])},setGlobalProperties:function(e){this._gp=e},onChartsReady:function(e){this._ocrq=this._ocrq||[],this._ocrq.push(e)}};(function(){var e=document.createElement("script");e.type="text/javascript",e.async=!0,e.src=("https:"==document.location.protocol?"https://":"http://")+"dc8na2hxrj29i.cloudfront.net/code/keen-2.1.0-min.js";var t=document.getElementsByTagName("script")[0];t.parentNode.insertBefore(e,t)})();
    // Configure the Keen object with your Project ID and (optional) access keys.
    Keen.configure({
    projectId: $S.global_conf.KEEN_IO_PROJECT_ID,
    writeKey: $S.global_conf.KEEN_IO_WRITE_KEY
    });
    
    var _strk = _strk || []
    window.runAfterDomBinding = {
      add: function(name, fn) {
        _strk.push(['Page.didMount', fn])
      }
    }
    
    window.strkHooks = {
      subscribe: function(eventName, cb) {
        _strk.push([eventName, cb])
      }
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html
    itemscope=""
    itemtype="http://schema.org/WebPage"
    lang="en"
    xmlns:fb="https://www.facebook.com/2008/fbml"
    xmlns:og="http://ogp.me/ns#"
    xmlns="http://www.w3.org/1999/xhtml"
    class="">
<head>
    <meta content="text/html; charset=UTF-8" http-equiv="Content-Type">
    <meta content="width=device-width,initial-scale=1.0,user-scalable=yes,minimum-scale=1.0,maximum-scale=3.0" id="viewport" name="viewport">
    <link rel="canonical" href="<%= $app_url %>">
    <title><%= $app_title %></title>
    <%#= render partial: 'js/cdata', layout: false %>
    
    <!--meta attributes-->
    <meta content="<%= $app_title %>" property="og:title">
    <meta content="<%= $app_url %>" property="og:url">
    <meta content="<%= $app_logo_path %>" property="og:image">
    <meta content="<%= $app_title %>" property="og:site_name">
    <meta content="<%= $app_description %>" property="og:description">
    <meta content="<%= $app_title %>" itemprop="name">
    <meta content="" itemprop="description">
    <meta content="<%= $app_logo_path %>" itemprop="image">
    <meta content="" name="description">
    <meta name="support-helper" content="{&quot;permalink&quot;:&quot;sambok&quot;,&quot;id&quot;:11348244}">
    <meta name="asset-url" content="<%= $app_url %>">
    
    <!--javascript importer first group-->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="https://bam.nr-data.net/1/74f55de04c?a=4870173&amp;v=998.365d633&amp;to=IlcLQxBeWFoHShYWSgRKOkQLRVFFTUtRDE4%3D&amp;rst=3734&amp;ref=http://sambok.strikingly.com/&amp;qt=1&amp;ap=310&amp;be=1010&amp;fe=1981&amp;dc=1232&amp;af=err,xhr,stn,ins,spa&amp;perf=%7B%22timing%22:%7B%22of%22:1482931513862,%22n%22:0,%22f%22:231,%22dn%22:231,%22dne%22:231,%22c%22:231,%22ce%22:231,%22rq%22:238,%22rp%22:838,%22rpe%22:844,%22dl%22:840,%22di%22:2238,%22ds%22:2238,%22de%22:2267,%22dc%22:2983,%22l%22:2991,%22le%22:2993%7D,%22navigation%22:%7B%7D%7D&amp;at=GhoQFVhKFlAXVFU8TBNURw1AWUBCEgIWTEoAVQdYCR9HQhBRUgpXBlQcGQFeWRlARUQ%3D&amp;jsonp=NREUM.setToken"></script>
    <script src="//d15qhc0lu1ghnk.cloudfront.net/beacon.js" async=""></script>
    <script src="https://js-agent.newrelic.com/nr-spa-998.min.js"></script>
    <script type="text/javascript" async="" src="http://dc8na2hxrj29i.cloudfront.net/code/keen-2.1.0-min.js"></script>
    
    
    <!--javascript setter-->
    <%= render partial: 'js/first', layout: false %>
    <%= render partial: 'js/second', layout: false %>
    <%#= render partial: 'js/googleapis', layout: false %>
    <script>
        (function() {
          window.$B || (window.$B = {});
        }).call(this);
    </script>
    
    <!--javascript importer second group-->
    <script src="/asset/header/js/detect.js" async="async"></script>
    <script type="text/javascript" charset="utf-8" async="" src="/asset/header/js/bundle_1_1.js"></script>
    <script type="text/javascript" charset="utf-8" async="" src="/asset/header/js/bundle_2_2.js"></script>
    <script type="text/javascript" charset="utf-8" async="" src="/asset/header/js/bundle_3_1.js"></script>
    <script type="text/javascript" charset="utf-8" async="" src="/asset/header/js/bundle_4_1.js"></script>
    
    <!--stylesheet importer group-->
    <link rel="stylesheet" media="screen" href="/asset/header/css/reset.css">
    <link rel="stylesheet" media="screen" href="//fonts.googleapis.com/css?family=Raleway:300,700|Roboto:300,700,300italic,700italic|Roboto+Condensed:300,700&amp;subset=latin,latin-ext">
    <link rel="stylesheet" media="screen" href="/asset/header/css/main2.css">
    
    <!--style sheet setter-->
    <style type="text/css">.fancybox-margin{margin-right:17px;}</style>
    <noscript>
        <style>.s-entrance-mask .s-section .container { opacity: 1 !important; }</style>
    </noscript>
    
    <!--core image setter-->
    <%#= $app_logo_path %>
    <link href="/asset/header/img/favicon.png" rel="shortcut icon" type="image/x-icon">
    <link href="/asset/header/img/logo_60.png" rel="apple-touch-icon" sizes="60x60">
    <link href="/asset/header/img/logo_76.png" rel="apple-touch-icon" sizes="76x76">
    <link href="/asset/header/img/logo_120.png" rel="apple-touch-icon" sizes="120x120">
    <link href="/asset/header/img/logo_152.png" rel="apple-touch-icon" sizes="152x152">
    
    <!--[if lte IE 9]>
    <link rel="stylesheet" media="screen" href="https://assets.strikingly.com/assets/themes/bright/main_v4_split2-8e25ac83d2cf201a805dfa9af872c097.css"/>
    <![endif]--> 
    <!--[if lte IE 10]>
    <link rel="stylesheet" media="screen" href="https://assets.strikingly.com/assets/ie8-f9a65d3da9d7965229bfd05f17b3ccfa.css"/>
    <![endif]--> 
    
    <!--other resources-->
</head>
<body class="show locale-en" id="user_sites" ontouchstart="" screen_capture_injected="true" style="overflow: auto;">

<%= yield %>

</body>
</html>

app/views/layouts/sambok.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Site Config</title>
        <%= csrf_meta_tags %>

        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

        <!-- 합쳐지고 최소화된 최신 CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">

        <!-- 부가적인 테마 -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap-theme.min.css">

        <!-- 합쳐지고 최소화된 최신 자바스크립트 -->
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js"></script>
    </head>

    <body style="background-color: #f88d98">
        <%= yield %>
    </body>
</html>

app/views/samboks/_form.html.erb
<%= form_for(@sambok) do |f| %>
  <% if @sambok.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sambok.errors.count, "error") %> prohibited this sambok from being saved:</h2>

      <ul>
      <% @sambok.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, style: 'width: 100%' %>
  </div>
  <div class="field">
    <%= f.label :slogan %><br>
    <%= f.text_field :slogan, style: 'width: 100%' %>
  </div>
  <div class="field">
    <%= f.label :img_path %><br>
    <%= f.text_field :img_path, style: 'width: 100%' %>
  </div>
  <div class="actions">
    <%= f.submit 'Update!', class: 'btn btn-warning' %>
  </div>
<% end %>

app/views/samboks/edit.html.erb
<div class="container">
    <h1>Editing Sambok</h1>

    <%= render 'form' %>

    <%#= link_to 'Show', @sambok %>
    <%= link_to '돌아가기', samboks_path %>
</div>

app/views/samboks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Samboks Main Information</h1> <%= link_to '홈으로 돌아가기', root_path, class: 'btn btn-primary', style: 'color: #fff' %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Slogan</th>
      <th>Img path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samboks.each do |sambok| %>
      <tr>
        <td><%= sambok.name %></td>
        <td><%= sambok.slogan %></td>
        <td><%= sambok.img_path %></td>
        <td><%= link_to '수정하기', edit_sambok_path(sambok), class: 'btn btn-warning btn-sm', style: 'color: #ffffff' %></td>
        <!--<td><%#= link_to 'Show', sambok %></td>-->
        <!--<td><%#= link_to 'Destroy', sambok, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>

<table class="table table-striped">
    <thead>
    <tr>
        <th>Name</th>
        <th>Subtitle</th>
        <th>Subtitle size</th>
        <th>Subtitle2</th>
        <th>Subtitle2 size</th>
        <th>Content</th>
        <th>Img path</th>
        <th>Bg img path</th>
        <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @sections.each do |section| %>
        <tr>
            <td><%= section.name %></td>
            <td><%= section.subtitle %></td>
            <td><%= section.subtitle_size %></td>
            <td><%= section.subtitle2 %></td>
            <td><%= section.subtitle2_size %></td>
            <td><%= section.content.truncate(20) %></td>
            <td><%= section.img_path %></td>
            <td><%= section.bg_img_path %></td>
            <td><%= link_to '수정하기', edit_section_path(section), class: 'btn btn-warning btn-sm', style: 'color: #ffffff' %></td>
            <!--<td><%#= link_to 'Show', section %></td>-->
            <!--<td><%#= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
        </tr>
    <% end %>
    </tbody>
</table>

<br>

<%#= link_to 'New Sambok', new_sambok_path %>

app/views/samboks/new.html.erb
<div class="container">
    <h1>New Sambok</h1>

    <%= render 'form' %>

    <%= link_to 'Back', samboks_path %>
    <%= link_to 'Home', root_path %>
</div>

app/views/samboks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @sambok.name %>
</p>

<p>
  <strong>Slogan:</strong>
  <%= @sambok.slogan %>
</p>

<p>
  <strong>Img path:</strong>
  <%= @sambok.img_path %>
</p>

<%= link_to 'Edit', edit_sambok_path(@sambok) %> |
<%= link_to 'Back', samboks_path %>

app/views/sections/_form.html.erb
<%= form_for(@section) do |f| %>
  <% if @section.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@section.errors.count, "error") %> prohibited this section from being saved:</h2>

      <ul>
      <% @section.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subtitle %><br>
    <%= f.text_field :subtitle %>
  </div>
  <div class="field">
    <%= f.label :subtitle_size %><br>
    <%= f.number_field :subtitle_size %>
  </div>
  <div class="field">
    <%= f.label :subtitle2 %><br>
    <%= f.text_field :subtitle2 %>
  </div>
  <div class="field">
    <%= f.label :subtitle2_size %><br>
    <%= f.number_field :subtitle2_size %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, style: 'width: 100%' %>
  </div>
  <div class="field">
    <%= f.label :img_path %><br>
    <%= f.text_field :img_path %>
  </div>
  <div class="field">
    <%= f.label :bg_img_path %><br>
    <%= f.text_field :bg_img_path %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sections/edit.html.erb
<div class="container">
    <h1>Editing Section</h1>

    <%= render 'form' %>

    <%#= link_to 'Show', @section %> |
    <%= link_to '돌아가기', samboks_path %>
</div>

app/views/sections/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sections</h1>
<%= link_to '홈으로 돌아가기', root_path %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Subtitle</th>
      <th>Subtitle size</th>
      <th>Subtitle2</th>
      <th>Subtitle2 size</th>
      <th>Content</th>
      <th>Img path</th>
      <th>Bg img path</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sections.each do |section| %>
      <tr>
        <td><%= section.name %></td>
        <td><%= section.subtitle %></td>
        <td><%= section.subtitle_size %></td>
        <td><%= section.subtitle2 %></td>
        <td><%= section.subtitle2_size %></td>
        <td><%= section.content.truncate(20) %></td>
        <td><%= section.img_path %></td>
        <td><%= section.bg_img_path %></td>
        <td><%= link_to '수정하기', edit_section_path(section), class: 'btn btn-warning btn-sm', style: 'color: #ffffff' %></td>
        <!--<td><%#= link_to 'Show', section %></td>-->
        <!--<td><%#= link_to 'Destroy', section, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Section', new_section_path %>

app/views/sections/new.html.erb
<div class="container">
    <h1>New Section</h1>
    <%= link_to '홈으로 돌아가기', root_path %>

    <%= render 'form' %>

    <%= link_to 'Back', sections_path %>
</div>

app/views/sections/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @section.name %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @section.subtitle %>
</p>

<p>
  <strong>Subtitle size:</strong>
  <%= @section.subtitle_size %>
</p>

<p>
  <strong>Subtitle2:</strong>
  <%= @section.subtitle2 %>
</p>

<p>
  <strong>Subtitle2 size:</strong>
  <%= @section.subtitle2_size %>
</p>

<p>
  <strong>Content:</strong>
  <%= @section.content %>
</p>

<p>
  <strong>Img path:</strong>
  <%= @section.img_path %>
</p>

<p>
  <strong>Bg img path:</strong>
  <%= @section.bg_img_path %>
</p>

<%= link_to 'Edit', edit_section_path(@section) %> |
<%= link_to 'Back', sections_path %>